// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ4pWTZHIkqPIeO-5tPw48_eVflVSf0hk',
    appId: '1:600464634853:web:2615d81c9ee7a67bc8350c',
    messagingSenderId: '600464634853',
    projectId: 'fine-foods-b891f',
    authDomain: 'fine-foods-b891f.firebaseapp.com',
    storageBucket: 'fine-foods-b891f.firebasestorage.app',
    measurementId: 'G-EHLCTPBDEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIkVqbPk5VfFP7tC0auKf8EGRbcMGls2s',
    appId: '1:600464634853:android:67faa830e8f0f2bcc8350c',
    messagingSenderId: '600464634853',
    projectId: 'fine-foods-b891f',
    storageBucket: 'fine-foods-b891f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArPvlWyubvcNlTTelzI74p8jd-BrDwBVo',
    appId: '1:600464634853:ios:cfbb9d9c17d43c90c8350c',
    messagingSenderId: '600464634853',
    projectId: 'fine-foods-b891f',
    storageBucket: 'fine-foods-b891f.firebasestorage.app',
    iosBundleId: 'com.example.fineFoods',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ4pWTZHIkqPIeO-5tPw48_eVflVSf0hk',
    appId: '1:600464634853:web:75c535430d47f89fc8350c',
    messagingSenderId: '600464634853',
    projectId: 'fine-foods-b891f',
    authDomain: 'fine-foods-b891f.firebaseapp.com',
    storageBucket: 'fine-foods-b891f.firebasestorage.app',
    measurementId: 'G-R0YB99NLL3',
  );

}